[project]
name = "playing-games"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib<3.9",
    "scipy>=1.17.0",
    "torch>=2.10.0",
    "yfinance>=1.1.0",
]
